spring:  
  mvc:  
    view:             # JSP views
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: 'true'
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
        

server:
  port: 8080